routes/web.php
<?php

use App\Http\Controllers\admin\ImageController;
use App\Http\Controllers\admin\VideoController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\admin\Auth\LoginController;
use App\Http\Controllers\VideoController as HomeVideo;
use App\Http\Controllers\ImageController as HomeImage;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::get('/image', [HomeImage::class, 'images'])->name('images');
Route::get('/videos', [HomeVideo::class, 'videos'])->name('videos');
Route::get('/sitemap.xml', [HomeController::class, 'sitemap'])->name('sitemap');
// Route::POST('test_mail', [HomeController::class, 'testMail'])->name('test_mail');


Route::prefix('admin')->group(function () {
    #Login
    Route::get('/login', [LoginController::class, 'show'])->name('admin.login');
    Route::post('/login', [LoginController::class, 'do']);
    #Logout
    Route::get('/logout', [LoginController::class, 'logout']);

    #Start AUTH
    Route::middleware('admin')->group(function () {
        #dashboard
        Route::get('/dashboard', [AdminController::class, 'index'])->name('admin.dashboard');
        #video
        Route::resource('/videos', VideoController::class);
        #image
        Route::resource('/images', ImageController::class);
        #profile
        Route::get('/profile', [AdminController::class, 'profile']);
        #profile save
        Route::post('/doprofile', [AdminController::class, 'doprofile']);

        #profile password save
        Route::post('/password', [AdminController::class, 'password']);


        #####################################################################
    }
    );
});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Image extends Model
{
    protected $table='images';
    use SoftDeletes,HasFactory;
    protected $fillable = [
        'date',
    ];
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Image;
use Illuminate\Http\Request;

class ImageController extends Controller
{
    public function images()
    {
        $style = "images.css";
        $pageTitle="دکتر علیرضا علمداری | عمل ترمیمی بینی| عکس عمل بینی| عکس قبل و بعد عمل بینی | بهترین دکتر زیبایی بینی | فلوشیپ جراحی زیبایی بینی و متخصص جراحی گوش و حلق و بینی";

        if (isset(request()->type)) {
            $images =  Image::where('type', request()->type)->whereNull('deleted_at')->orderBy('id','DESC')->get();
        } else {

            $images = Image::whereNull('deleted_at')->orderBy('id','DESC')->get();
        }
        return view('images', ['style' => $style,'pageTitle'=>$pageTitle, 'images' => $images]);
    }
}

app/Http/Controllers/admin/ImageController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ImageController extends Controller
{
    public function index()
    {
        
        $data['image'] =  Image::whereNull('deleted_at')->latest('id')->get();
        $data['title'] = 'لیست عکسها';
        $data['url'] = '';
        $data['auth'] = Auth::guard('admin')->user();

        return view('admin.image.index', $data);
    }

    public function create()
    {
        $data['title'] = 'ثبت عکس';

        $data['url'] = '';
        $data['auth'] = Auth::guard('admin')->user();
        $url = "/images/poioi.jpg";
        return view('admin.image.create', $data);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'date' => 'required',
            'tamamrokh' => 'required|file|mimes:png,jpeg,jpg',
            'nimrokh' => 'required|file|mimes:png,jpeg,jpg',

        ]);

        $nimrokhName = $request->nimrokh->getClientOriginalName();
        $nimrokhPath = 'pictures/' . $nimrokhName;
        if (!Storage::disk('public')->exists($nimrokhPath)) {
            $isnimrokhUploaded = Storage::disk('public')->put($nimrokhPath, file_get_contents($request->nimrokh));
        }


        $tamamrokhName = $request->tamamrokh->getClientOriginalName();
        $tamamrokhPath = 'pictures/' . $tamamrokhName;
        if (!Storage::disk('public')->exists($tamamrokhPath)) {
            $isTamamrokhUploaded = Storage::disk('public')->put($tamamrokhPath, file_get_contents($request->tamamrokh));
        }

        $existPic = Image::where('tamamrokh', $tamamrokhPath)->whereNull('deleted_at')->first();
        if (empty($existPic)) {
            $image = new Image();
            $image->type = $request->type;
            $image->date = $request->date;
            $image->tamamrokh = $tamamrokhPath;
            $image->nimrokh = $nimrokhPath;
            $image->save();

            return back()->with('msg', '   ثبت در سیستم انجام شد .');
        }

        return back()
            ->with('msg', 'Unexpected error occured');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //http://127.0.0.1:8000/learn/resource/10
        // nemayesh taki
        return 'show' . $id;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = 'ویرایش ';

        $data['image'] = Image::findOrFail($id);
        $data['auth'] = Auth::guard('admin')->user();

        $data['url'] = '';
        return view('admin.image.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $image = Image::findOrfail($id);
        #validate
        $this->validate($request, [
            'date' => 'required',
        ]);
        #file
        if ($request->hasFile('nimrokh')) {
            // dd($request->nimrokh->getClientOriginalName());
            $nimrokh = 'pictures/' . $request->nimrokh->getClientOriginalName();
            $image->nimrokh = $nimrokh;
            if (!Storage::disk('public')->exists($nimrokh)) {
                $isnimrokhUploaded = Storage::disk('public')->put($nimrokh, file_get_contents($request->nimrokh));
            }
        }
        if ($request->hasFile('tamamrokh')) {
            // dd($request->tamamrokh->getClientOriginalName());

            $tamamrokh = 'pictures/' . $request->tamamrokh->getClientOriginalName();
            $image->tamamrokh = $tamamrokh;
            if (!Storage::disk('public')->exists($tamamrokh)) {
                $istamamrokhUploaded = Storage::disk('public')->put($tamamrokh, file_get_contents($request->nimrokh));
            }
        }
        $image->date = $request->date;
        $image->type = $request->type;
        $image->update();
        return back()->with('msg', '  تغییرات با موفقیت انجام شد  .');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Image::destroy($id);
        return back()->with('msg', 'مخاطب حذف  شد.');
    }
}

resources/views/admin/image/create.blade.php
@extends('admin.master')
@section('content')
    <!--Panel-->
    <div class="panel panel-default" id="tabledb3">
        <div class="panel-heading">
            <div class="panel-title">ثبت <small>عکس</small>
            </div>
        </div>
        <div class="panel-body">
            <!-- Warning messages -->
            @include('admin.message')
            <form method="post" action="{{ route('images.store') }}" enctype="multipart/form-data" class="form-horizontal">
                @csrf

                <fieldset>
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-2  control-label "> تاریخ عمل</label>
                        <div class="col-md-10 ui-sortable">
                            <input required name="date" placeholder="اینجا بنویسید" class="form-control input-md"
                                type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2  control-label "> عکس تمام رخ </label>
                        <div class="col-md-10 ui-sortable">
                            <input type="file" name="tamamrokh" class="form-control" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2  control-label "> عکس نیم رخ </label>
                        <div class="col-md-10 ui-sortable">
                            <input type="file" name="nimrokh" class="form-control" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label"> موضوع</label>
                        <div class="col-md-9 ui-sortable">
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-0-normal-styled" value="nose" checked="checked"
                                    type="radio">
                                <label for="radios-inline-0-normal-styled">بینی</label>
                            </div>
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-1-normal-styled" value="ear" type="radio">
                                <label for="radios-inline-1-normal-styled">گوش</label>
                            </div>
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-2-normal-styled" value="other" type="radio">
                                <label for="radios-inline-2-normal-styled">دیگر</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group ">
                        <div class="col-md-3"></div>
                        <div class="col-md-6 ui-sortable">
                            <button type="submit" class="btn btn-block btn-success">
                                <i class="fa fa-2x fa-check"> </i>
                                ثبت در سیستم
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <!--/Panel Body-->
    </div>
    <!--/Panel-->
@endsection
@section('js')
    <script src="/assets/admin/my.js"></script>
    <style>
        .control-label {
            text-align: right !important;
        }
    </style>

    <script type="text/javascript" src="/assets/admin/js/vendors/parsley/parsley-config.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/parsley/parsley.min.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/parsley/comparison.js"></script>
@endsection

resources/views/admin/image/edit.blade.php
@extends('admin.master')
@section('content')
    <!--Panel-->
    <div class="panel panel-default" id="tabledb3">
        <div class="panel-heading">
            <div class="panel-title">ویرایش <small>عکس</small>
            </div>

        </div>
        <div class="panel-body">
            <!-- Warning messages -->
            @include('admin.message')
            <form method="post" action="{{ route('images.update', $image->id) }}" enctype="multipart/form-data"
                class="form-horizontal" data-parsley-validate>
                <fieldset>
                    <!-- Text input-->
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="form-group">
                        <label class="col-md-2  control-label "> تاریخ عمل/توضیحات </label>
                        <div class="col-md-10 ui-sortable">
                            <input required value="{{ $image->date }}" name="date" placeholder="اینجا بنویسید"
                                class="form-control input-md" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2  control-label "> عکس تمام رخ </label>
                        <div class="col-md-10 ui-sortable">
                            <img src="{{ asset('storage/public/' . $image->tamamrokh) }}" alt="عکس تمام رخ" style="width:10%">
                            <input type="file" name="tamamrokh" value="{{ $image->tamamrokh }}" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2  control-label "> عکس نیم رخ </label>
                        <div class="col-md-10 ui-sortable d-flex flex-row">
                            <img src="{{ asset('storage/public/' . $image->nimrokh) }}" alt="عکس نیم رخ"
                                style="width:10%;height:10%;">
                                {{-- @dd(asset($image->nimrokh)) --}}
                            <input type="file" name="nimrokh" value="{{asset($image->nimrokh) }}" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label"> موضوع</label>
                        <div class="col-md-9 ui-sortable">
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-0-normal-styled" value="nose"
                                    @if ($image->type == 'nose') checked="checked" @endif type="radio">
                                <label for="radios-inline-0-normal-styled">بینی</label>
                            </div>
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-1-normal-styled" value="hear"
                                    @if ($image->type == 'ear') checked="checked" @endif type="radio">
                                <label for="radios-inline-1-normal-styled">گوش</label>
                            </div>
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-2-normal-styled" value="other"
                                    @if ($image->type == 'other') checked="checked" @endif type="radio">
                                <label for="radios-inline-2-normal-styled">دیگر</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-md-3"></div>
                        <div class="col-md-6 ui-sortable">
                            <button type="submit" class="btn btn-block btn-success">
                                <i class="fa fa-2x fa-check"> </i>
                                ثبت در سیستم
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
        <!--/Panel Body-->
    </div>
    <!--/Panel-->
@endsection
@section('js')
    <script src="{{ $url }}/assets/admin/my.js"></script>
    <style>
        .control-label {
            text-align: right !important;
        }
    </style>
    {{-- upload --}}
    <link rel="stylesheet" href="{{ $url }}/assets/admin/dropify/dist/css/dropify.min.css">
    <script src="{{ $url }}/assets/admin/dropify/dist/js/dropify.min.js"></script>
    <script>
        $('.dropify').dropify({
            messages: {
                default: 'یک فایل اینجا بکشید و یا کلیک کنید',
                replace: 'برای جایگزینی ، یک فایل اینجا بکشید و یا کلیک کنید',
                remove: 'حذف',
                error: 'خطا در ارسال فایل',
            }
        });
    </script>

    {{-- validataion --}}
    <!--Parsley-->
    <script type="text/javascript" src="{{ $url }}/assets/admin/js/vendors/parsley/parsley-config.js"></script>
    <script type="text/javascript" src="{{ $url }}/assets/admin/js/vendors/parsley/parsley.min.js"></script>
    <script type="text/javascript" src="{{ $url }}/assets/admin/js/vendors/parsley/comparison.js"></script>

    {{-- slect2 --}}
    <link rel="stylesheet" href="{{ $url }}/assets/admin/select2/select2.min.css">
    <script src="{{ $url }}/assets/admin/select2/select2.min.js"></script>
    <script>
        $('.select2').select2({
            width: '100%',
            dir: "rtl",
        });
    </script>
    <style>
        .select2-selection__rendered {
            background-color: #dee1e6;
        }
    </style>
@endsection

resources/views/admin/image/index.blade.php
@extends('admin.master')
@section('content')
    <div class="panel panel-default" id="tabledb3">
        <div class="panel-heading">
            <div class="panel-title">لیست <small>عکسها</small>
            </div>
        </div>
        <div class="panel-body">
            <form action="{{ route('images.create') }}">
                <button class="btn btn-primary" type="submit"> create </button>
            </form>

            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="table-responsive">
                <table id="datatablesexample3" class="table table-striped">
                    <thead>
                        <tr>
                            <th> تاریخ عمل/توضیحات </th>
                            <th> عکس تمام رخ </th>
                            <th> عکس نیم رخ </th>
                            <th> عملیات </th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th> تاریخ عمل/توضیحات </th>
                            <th> عکس تمام رخ </th>
                            <th> عکس نیم رخ </th>
                            <th> عملیات </th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($image as $item)
                            <tr>
                                <td>{{ $item->date }}</td>
                                <td><img src="{{ asset('storage/' . $item->tamamrokh) }}" alt="عکس تمام رخ" style="width:20%"></td>
                                <td><img src="{{ asset('storage/' . $item->nimrokh) }}" alt="عکس نیم رخ" style="width:20%"></td>
                                <td class="text-center">
                                    <a href="{{ route('images.edit', $item->id) }}" data-toggle="tooltip"
                                        data-placement="right" data-original-title="ویرایش"
                                        class="fa fa-pencil  tooltiped text-warning">
                                    </a>
                                    <form method="post" style="display: inline !important;" action="{{route('images.destroy',$item->id)}}">
                                        @csrf
                                        {{ method_field('delete') }}
                                        <button type="button" data-toggle="tooltip" data-placement="right" data-original-title="حذف کن" class="fa fa-trash tooltiped text-danger btntable"></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <!--/Panel Body-->
    </div>
@endsection
@section('js')
    <!--Datatables-->
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/dataTables.colReorder.min.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/datatables-examples.js"></script>
@endsection