routes/web.php
<?php

use App\Http\Controllers\admin\ImageController;
use App\Http\Controllers\admin\VideoController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\admin\Auth\LoginController;
use App\Http\Controllers\VideoController as HomeVideo;
use App\Http\Controllers\ImageController as HomeImage;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::get('/image', [HomeImage::class, 'images'])->name('images');
Route::get('/videos', [HomeVideo::class, 'videos'])->name('videos');
Route::get('/sitemap.xml', [HomeController::class, 'sitemap'])->name('sitemap');
// Route::POST('test_mail', [HomeController::class, 'testMail'])->name('test_mail');


Route::prefix('admin')->group(function () {
    #Login
    Route::get('/login', [LoginController::class, 'show'])->name('admin.login');
    Route::post('/login', [LoginController::class, 'do']);
    #Logout
    Route::get('/logout', [LoginController::class, 'logout']);

    #Start AUTH
    Route::middleware('admin')->group(function () {
        #dashboard
        Route::get('/dashboard', [AdminController::class, 'index'])->name('admin.dashboard');
        #video
        Route::resource('/videos', VideoController::class);
        #image
        Route::resource('/images', ImageController::class);
        #profile
        Route::get('/profile', [AdminController::class, 'profile']);
        #profile save
        Route::post('/doprofile', [AdminController::class, 'doprofile']);

        #profile password save
        Route::post('/password', [AdminController::class, 'password']);


        #####################################################################
    }
    );
});

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Video extends Model
{
    protected $table='videos';
    use SoftDeletes;
    use HasFactory;
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Video;
use Illuminate\Http\Request;

class VideoController extends Controller
{
    public function videos()
    {
        $style = "videos.css";
        $pageTitle="دکتر علیرضا علمداری |ویدیوهای جراحی زیبایی بینی| ویدیو عمل بینی گوشتی | بهترین جراح زیبایی | فلوشیپ جراحی زیبایی بینی و متخصص جراحی گوش و حلق و بینی";

        if (isset(request()->type)) {
            $videos =  Video::where('type', request()->type)->whereNull('deleted_at')->orderBy('id','DESC')->get();
        } else {
            $videos = Video::whereNull('deleted_at')->orderBy('id','DESC')->get();
        }
        return view('videos', ['style' => $style,'pageTitle'=>$pageTitle, 'videos' => $videos]);
    }
}

app/Http/Controllers/admin/VideoController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Video;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class VideoController extends Controller
{
    public function index()
    {
       
        $data['video'] =  Video::whereNull('deleted_at')->latest('id')->get();
        $data['title'] = 'لیست ویدیوها';
        $data['url'] = '';
        $data['auth'] = Auth::guard('admin')->user();

        return view('admin.video.index', $data);
    }

    public function create()
    {
        $data['title'] = 'ثبت ویدیو';

        $data['url'] = '';
        $data['auth'] = Auth::guard('admin')->user();
        $url = "/images/poioi.jpg";
        return view('admin.video.create', $data);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'image' => 'required',
            'video' => 'required|file|mimes:mp4,mov,MOV,ogv',
        ]);
        $videoName = $request->video->getClientOriginalName();
        $videoPath = 'videos/' . $videoName;
        if (!Storage::disk('public')->exists($videoPath)) {
            $isVideoUploaded = Storage::disk('public')->put($videoPath, file_get_contents($request->video));
        }

        $imageName = $request->image->getClientOriginalName();
        $imagePath = 'images/' . $imageName;

        if (!Storage::disk('public')->exists($imagePath)) {
            $isImageUploaded = Storage::disk('public')->put($imagePath, file_get_contents($request->image));
        }
        $existVideo = Video::where('video', $videoPath)->whereNull('deleted_at')->first();
        if (empty($existVideo)) {
            $video = new Video();
            $video->type = $request->type;
            $video->date = $request->date;
            $video->video = $videoPath;
            $video->image = $imagePath;
            $video->save();
            return back()->with('msg', '   ثبت در سیستم انجام شد .');
        }

        return back()
            ->with('msg', 'Unexpected error occured');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //http://127.0.0.1:8000/learn/resource/10
        // nemayesh taki
        return 'show' . $id;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = 'ویرایش ';

        $data['video'] = Video::findOrFail($id);
        $data['auth'] = Auth::guard('admin')->user();

        $data['url'] = '';
        return view('admin.video.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $videoSelected = Video::findOrfail($id);
        $this->validate($request, [
            'date' => 'required',
        ]);
        #file
        if ($request->hasFile('image')) {
            $image = 'images/' . $request->image->getClientOriginalName();
            $videoSelected->image = $image;
            if (!Storage::disk('public')->exists($image)) {
                $isimageUploaded = Storage::disk('public')->put($image, file_get_contents($request->image));
            }
        }
        if ($request->hasFile('video')) {
            $video = 'videos/' . $request->video->getClientOriginalName();
            $videoSelected->video = $video;
            if (!Storage::disk('public')->exists($video)) {
                $isimageUploaded = Storage::disk('public')->put($video, file_get_contents($request->video));
            }
        }

        $videoSelected->date = $request->date;
        $videoSelected->type = $request->type;

        $videoSelected->update();
        return back()->with('msg', '  تغییرات با موفقیت انجام شد  .');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Video::destroy($id);
        return back()->with('msg', 'مخاطب حذف  شد.');
    }
}

resources/views/admin/video/create.blade.php
@extends('admin.master')
@section('content')

<!--Panel-->
<div class="panel panel-default" id="tabledb3">
    <div class="panel-heading">
        <div class="panel-title">ثبت <small>ویدیو</small>
        </div>
    </div>
    <div class="panel-body">
        <!-- Warning messages -->
        @include('admin.message')
        <form method="post" action="{{route('videos.store')}}" enctype="multipart/form-data" class="form-horizontal">
            @csrf

            <fieldset>
                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-2  control-label "> تاریخ عمل</label>
                    <div class="col-md-10 ui-sortable">
                        <input required name="date" placeholder="اینجا بنویسید" class="form-control input-md" type="text">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2  control-label "> عکس </label>
                    <div class="col-md-10 ui-sortable">
                        <input type="file" name="image" class="form-control" required/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2  control-label "> ویدیو </label>
                    <div class="col-md-10 ui-sortable">
                        <input type="file" name="video" class="form-control" required/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"> موضوع</label>
                    <div class="col-md-9 ui-sortable">
                        <div class="radio-styled radio-inline">
                            <input name="type" id="radios-inline-0-normal-styled" value="nose" checked="checked" type="radio">
                            <label for="radios-inline-0-normal-styled">بینی</label>
                        </div>
                        <div class="radio-styled radio-inline">
                            <input name="type" id="radios-inline-1-normal-styled" value="ear" type="radio">
                            <label for="radios-inline-1-normal-styled">گوش</label>
                        </div>
                        <div class="radio-styled radio-inline">
                            <input name="type" id="radios-inline-2-normal-styled" value="other" type="radio">
                            <label for="radios-inline-2-normal-styled">دیگر</label>
                        </div>
                    </div>
                </div>

                <div class="form-group ">
                    <div class="col-md-3"></div>
                    <div class="col-md-6 ui-sortable">
                        <button type="submit" class="btn btn-block btn-success">
                            <i class="fa fa-2x fa-check"> </i>
                            ثبت در سیستم
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <!--/Panel Body-->
</div>
<!--/Panel-->

@endsection
@section('js')
<script src="/assets/admin/my.js"></script>
<style>
    .control-label {
        text-align: right !important;
    }
</style>

{{-- <script type="text/javascript" src="/assets/admin/js/vendors/parsley/parsley-config.js"></script>
<script type="text/javascript" src="/assets/admin/js/vendors/parsley/parsley.min.js"></script>
<script type="text/javascript" src="/assets/admin/js/vendors/parsley/comparison.js"></script> --}}

@endsection

resources/views/admin/video/edit.blade.php
@extends('admin.master')
@section('content')
    <!--Panel-->
    <div class="panel panel-default" id="tabledb3">
        <div class="panel-heading">
            <div class="panel-title">ویرایش <small>پزشک</small>
            </div>

        </div>
        <div class="panel-body">
            <!-- Warning messages -->
            @include('admin.message')
            <form method="post" action="{{ route('videos.update', $video->id) }}" enctype="multipart/form-data"
                class="form-horizontal" data-parsley-validate>
                <fieldset>
                    <!-- Text input-->
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="form-group">
                        <label class="col-md-2  control-label "> توضیحات</label>
                        <div class="col-md-10 ui-sortable">
                            <input required value="{{ $video->date }}" name="date" placeholder="اینجا بنویسید"
                                class="form-control input-md" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2  control-label "> عکس </label>
                        <div class="col-md-10 ui-sortable">
                            <img src="{{ asset('storage/public/' . $video->image) }}" alt="عکس" style="width:10%">
                            <input type="file" name="image" class="form-control" value="{{($video->image)}}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2  control-label "> ویدیو </label>
                        <div class="col-md-10 ui-sortable">
                            <input type="file" name="video" class="form-control" value="{{('storage/public/' .$video->video)}}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label"> موضوع</label>
                        <div class="col-md-9 ui-sortable">
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-0-normal-styled" value="nose"
                                    @if ($video->type == 'nose') checked="checked" @endif type="radio">
                                <label for="radios-inline-0-normal-styled">بینی</label>
                            </div>
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-1-normal-styled" value="hear"
                                    @if ($video->type == 'ear') checked="checked" @endif type="radio">
                                <label for="radios-inline-1-normal-styled">گوش</label>
                            </div>
                            <div class="radio-styled radio-inline">
                                <input name="type" id="radios-inline-2-normal-styled" value="other"
                                    @if ($video->type == 'other') checked="checked" @endif type="radio">
                                <label for="radios-inline-2-normal-styled">دیگر</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-md-3"></div>
                        <div class="col-md-6 ui-sortable">
                            <button type="submit" class="btn btn-block btn-success">
                                <i class="fa fa-2x fa-check"> </i>
                                ثبت در سیستم
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
        <!--/Panel Body-->
    </div>
    <!--/Panel-->
@endsection
@section('js')
    <script src="/assets/admin/my.js"></script>
    <style>
        .control-label {
            text-align: right !important;
        }
    </style>
    {{-- upload --}}
    <link rel="stylesheet" href="/assets/admin/dropify/dist/css/dropify.min.css">
    <script src="/assets/admin/dropify/dist/js/dropify.min.js"></script>
    <script>
        $('.dropify').dropify({
            messages: {
                default: 'یک فایل اینجا بکشید و یا کلیک کنید',
                replace: 'برای جایگزینی ، یک فایل اینجا بکشید و یا کلیک کنید',
                remove: 'حذف',
                error: 'خطا در ارسال فایل',
            }
        });
    </script>

    {{-- validataion --}}
    <!--Parsley-->
    <script type="text/javascript" src="/assets/admin/js/vendors/parsley/parsley-config.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/parsley/parsley.min.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/parsley/comparison.js"></script>

    {{-- slect2 --}}
    <link rel="stylesheet" href="/assets/admin/select2/select2.min.css">
    <script src="/assets/admin/select2/select2.min.js"></script>
    <script>
        $('.select2').select2({
            width: '100%',
            dir: "rtl",
        });
    </script>
    <style>
        .select2-selection__rendered {
            background-color: #dee1e6;
        }
    </style>
@endsection

resources/views/admin/video/index.blade.php
@extends('admin.master')
@section('content')
    <!--Panel-->
    <div class="panel panel-default" id="tabledb3">
        <div class="panel-heading">
            <div class="panel-title">لیست <small>ویدیوها</small>
            </div>

        </div>
        <div class="panel-body">
            <form action="{{ route('videos.create') }}">
                <button class="btn btn-primary" type="submit"> create </button>
            </form>

            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif

            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="table-responsive">
                <table id="datatablesexample3" class="table table-striped">
                    <thead>
                        <tr>
                            <th> عکس </th>
                            <th> ویدیو </th>
                            <th> عملیات </th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th> عکس </th>
                            <th> ویدیو </th>
                            <th> عملیات </th>
                        </tr>
                    </tfoot>

                    <tbody>
                        @foreach ($video as $item)
                            <tr>
                                <td><img src="{{ asset('storage/' . $item->image) }}" alt="video poster" style="width:20%">
                                </td>
                                <td>{{ $item->video ?? '' }}</td>
                                <td class="text-center">
                                    <a href="{{ route('videos.edit', $item->id) }}" data-toggle="tooltip"
                                        data-placement="right" data-original-title="ویرایش"
                                        class="fa fa-pencil  tooltiped text-warning"></a>
                                
                                    <form method="post" style="display: inline !important;"
                                        action="{{ route('videos.destroy', $item->id) }}">
                                        @csrf
                                        {{ method_field('delete') }}
                                        <button type="button" data-toggle="tooltip" data-placement="right"
                                            data-original-title="حذف کن"
                                            class="fa fa-trash tooltiped text-danger btntable"></button>
                                    </form>
                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <!--/Panel Body-->
    </div>
    <!--/Panel-->

@endsection
@section('js')
    <!--Datatables-->
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/dataTables.colReorder.min.js"></script>
    <script type="text/javascript" src="/assets/admin/js/vendors/datatables/datatables-examples.js"></script>
@endsection